### ISSUE TITLE
data-bgcolor not changing Meter widget

### ISSUE THREAD

**Issue by justinmartin** [Shopify/dashing#613]
I have the following code:

```
<li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
    <div data-id="jh_host1_memory" data-view="Meter" data-title="JH Host1 Memory" data-min="0" data-max="33549244" data-bgcolor="#88C100"></div>
  </li>
```

However, the data-bgcolor attribute is not affecting the widget.  What am I missing?

**Comment by tylermauthe** [comment]
Looks like a bug, I've committed a fix.

**Comment by justinmartin** [comment]
That doesn't seem to fix it.  Now the input.meter color is a light blue, which I don't have set anywhere.

<img width="295" alt="screen shot 2015-09-09 at 2 52 09 pm" src="https://cloud.githubusercontent.com/assets/1242435/9772529/66c843ca-5702-11e5-8a43-96cd83423c3b.png">

**Comment by tylermauthe** [comment]
Sorry, this is not a bug. I jumped the gun and then cowboyed a pull request.

You should set some CSS on your widget to style it. Add a selector to the `li` tag around your widget and do something like this:

```css
.server-widget, .server-widget * {
  color: white;
  background-color: black !important;
}
```

**Comment by justinmartin** [comment]
OK. I'll do that.

What is the data-bgcolor for? I'm new to using data attributes.

**Comment by tylermauthe** [comment]
The data attribute is being set on the `input` element inside the widget, based on the widget's CSS colours. It is used by the [jQuery Knob](https://github.com/aterrien/jQuery-Knob) plugin to set the meter's colours.

Please close this issue if the solution works for you.
